name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run'  

jobs:
  Build_App_and_Push_Image:
    runs-on: [ubuntu-latest]
    steps:
      - 
        name: Fetch
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/quote_renderer:latest
          build-args: |
            NODE_PORT=2000
          platforms: linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Remove previous version
        uses:  kc1r74p/delete-package-versions@main
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'quote_renderer'
          package-type: 'container'
          ignore-tag: 'latest'
          token: ${{ secrets.CR_PAT }}
